apiVersion: v1
kind: Service
metadata:
  name: wil-playground
  labels:
    app: wil-playground
spec:
  selector:
    app: wil-playground
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
